version: 2.1

jobs:
  checks:
    docker:
      - image: corebreaker/rust-devtools-circleci:rust-1.96.0-v0.3.15
        auth:
          username: corebreaker
          password: $DOCKERHUB_ACCESS_TOKEN
    steps:
      - checkout
      - run:
          name: Show toolchain versions
          command: "rustc --version && cargo --version && cargo +nightly --version"
      - run:
          name: Check formatting
          command: "cargo +nightly fmt -- --config-path .rustfmt.toml --check"

  coverage:
    docker:
      - image: corebreaker/rust-devtools-circleci:rust-1.96.0-v0.3.15
        auth:
          username: corebreaker
          password: $DOCKERHUB_ACCESS_TOKEN
    steps:
      - checkout
      - run:
          name: Make coverage
          command: "coverage.sh"
      - run:
          name: Upload Coverage Result To Coveralls
          command: "coveralls circleci -r poreader -D target -t $COVERALLS_REPO_TOKEN target/coverage/coveralls.json"
      - store_artifacts:
          path: target/coverage

  test:
    docker:
      - image: cimg/rust:1.96.0
        auth:
          username: corebreaker
          password: $DOCKERHUB_ACCESS_TOKEN
    steps:
      - checkout
      - run:
          name: Run tests
          command: "CARGO_NET_GIT_FETCH_WITH_CLI=true cargo test --all-features --all-targets"
      - run:
          name: Run doctests
          command: "CARGO_NET_GIT_FETCH_WITH_CLI=true cargo test --all-features --doc"

workflows:
  coverage:
    jobs:
      - coverage

  all-tests:
    jobs:
      - checks
      - test
